version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/circle-tmp-folder
    steps:
      - run:
          name: build
          command: 'yarn build'
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync /home/ubuntu/goServerless s3://www.vamsipitta.com --delete